language: cpp
compiler:
    - gcc
notifications:
    email: false
env:
    - JULIAVERSION="julianightlies" 
    - JULIAVERSION="juliareleases" 
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
    - sudo apt-get update -qq -y
    - sudo apt-get install julia -y
    - sudo apt-get install gfortran pkg-config
    - git config --global user.name "Travis User"
    - git config --global user.email "travis@example.net"
script:
    - julia -e 'Pkg.init();'
    - julia -e 'run(`ln -s $(pwd()) $(Pkg.dir("Ipopt"))`); Pkg.pin("Ipopt"); Pkg.resolve()'
    - julia -e 'Pkg.build("Ipopt")'
    - julia ./test/runtests.jl
