language: cpp
compiler:
    - gcc
notifications:
    email: false
env:
    - JULIAVERSION="juliareleases" 
    - JULIAVERSION="julianightlies"
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
    - sudo apt-get update -qq -y
    - sudo apt-get install gfortran libpcre3-dev julia -y
    - git config --global user.name "Travis User"
    - git config --global user.email "travis@example.net"
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
    - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.build("Ipopt")'
    - julia -e 'Pkg.test("Ipopt", coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("Ipopt")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
